### ISSUE TITLE
How can we install and use?

### ISSUE THREAD

**Issue by ugurbay** [vonadz/trader#1]
Hi. First of all, i thank you so much because of this repo. I am new at clojure. I can not find projects like that written in clojure and clojurescript. This is a good job but i could not find info about install and using this project. I will very glad for your help. Thanks so much.

**Comment by vonadz** [comment]
I wouldn't recommend using this. It has no functionality really, other than downloading tick data from Binance.

**Comment by ugurbay** [comment]
Thanks for your reply. If you have time to work for global jobs, i can work with you in some project. My mail: ugurbay@gmail.com
